#!/bin/bash
ORNG='\033[0;33m'
NC='\033[0m'
W='\033[1;37m'
LP='\033[1;35m'

echo -e "${LP}"
figlet RapidScan
echo -e "${NC}"
echo -e "${ORNG}Starting RapidScan Framework${NC}"
cd /opt/rapidscan
echo -e "${W}Please enter your target${NC}"
read TARGET
sleep 1
./rapidscan.py $TARGET 
echo -e "${W}When ready please hit enter${NC}"